CREATE TABLE Tourist_Spot (d_id int(10) NOT NULL AUTO_INCREMENT, d_name varchar(255) NOT NULL UNIQUE, pic varchar(255), description varchar(255), PRIMARY KEY (d_id));
CREATE TABLE Room_Booking (h_id int(10) NOT NULL AUTO_INCREMENT, h_name varchar(255) NOT NULL, room_id int(10) NOT NULL, price int(11) NOT NULL, availability binary(1) NOT NULL, user_id int(10) NOT NULL, Tourist_Spotd_id int(10) NOT NULL, PRIMARY KEY (h_id));
CREATE TABLE Rental_car (d_id int(10) NOT NULL, rent int(11), car_id int(10) NOT NULL AUTO_INCREMENT, car_model varchar(255), c_avail binary(1) NOT NULL, user_id int(10) NOT NULL, PRIMARY KEY (car_id));
CREATE TABLE Places_to_visit (d_id int(10), place_name varchar(255) NOT NULL, place_pic varchar(255), Tourist_Spotd_id int(10) NOT NULL);
CREATE TABLE Insurance (user_id int(10) NOT NULL, insurance_id int(10) NOT NULL AUTO_INCREMENT, health_price int(11), Things_price int(11), trip_cancel_price int(11), Health binary(1), things binary(1), trip_cancel binary(1), PRIMARY KEY (insurance_id));
CREATE TABLE user_profile (user_id int(10) NOT NULL AUTO_INCREMENT, user_name varchar(255), user_mail varchar(255) NOT NULL UNIQUE, password varchar(255) NOT NULL, user_balance float DEFAULT 0, PRIMARY KEY (user_id));
CREATE TABLE ticket_bboking (t_id int(10) NOT NULL AUTO_INCREMENT, d_id int(10) NOT NULL, t_avail binary(1) NOT NULL, time time NOT NULL, travel_medium varchar(255) NOT NULL, `date` date, t_price int(10) NOT NULL, Tourist_Spotd_id int(10) NOT NULL, user_id int(10) NOT NULL, Booking_count int(11) DEFAULT 0, PRIMARY KEY (t_id));
CREATE TABLE things_to_do (d_id int(10), description varchar(255) NOT NULL, ttd_id varchar(255) NOT NULL, PRIMARY KEY (ttd_id));
CREATE TABLE Packing_tips (d_id int(10) NOT NULL AUTO_INCREMENT, description varchar(255) NOT NULL, Tourist_Spotd_id int(10) NOT NULL, PRIMARY KEY (d_id));
CREATE TABLE Guide (g_iid int(10) NOT NULL AUTO_INCREMENT, g_name varchar(255) NOT NULL, description varchar(255), d_id int(10) NOT NULL, g_avail binary(1) NOT NULL, g_pic varchar(255), user_id int(10) NOT NULL, PRIMARY KEY (g_iid));
CREATE TABLE `things_to_do_Tourist Spot` (things_to_dottd_id varchar(255) NOT NULL, Tourist_Spotd_id int(10) NOT NULL, PRIMARY KEY (things_to_dottd_id, Tourist_Spotd_id));
CREATE TABLE Information (information_id int(10) NOT NULL AUTO_INCREMENT, h_id int(10) NOT NULL, room_id int(10), t_id int(10), car_id int(10), insurance_id int(10), PRIMARY KEY (information_id));
ALTER TABLE Packing_tips ADD INDEX FKPacking_ti894263 (Tourist_Spotd_id), ADD CONSTRAINT FKPacking_ti894263 FOREIGN KEY (Tourist_Spotd_id) REFERENCES Tourist_Spot (d_id);
ALTER TABLE Places_to_visit ADD INDEX FKPlaces_to_308030 (Tourist_Spotd_id), ADD CONSTRAINT FKPlaces_to_308030 FOREIGN KEY (Tourist_Spotd_id) REFERENCES Tourist_Spot (d_id);
ALTER TABLE `things_to_do_Tourist Spot` ADD INDEX FKthings_to_290669 (things_to_dottd_id), ADD CONSTRAINT FKthings_to_290669 FOREIGN KEY (things_to_dottd_id) REFERENCES things_to_do (ttd_id);
ALTER TABLE `things_to_do_Tourist Spot` ADD INDEX FKthings_to_291151 (Tourist_Spotd_id), ADD CONSTRAINT FKthings_to_291151 FOREIGN KEY (Tourist_Spotd_id) REFERENCES Tourist_Spot (d_id);
ALTER TABLE Room_Booking ADD INDEX FKRoom_Booki97234 (user_id), ADD CONSTRAINT FKRoom_Booki97234 FOREIGN KEY (user_id) REFERENCES user_profile (user_id);
ALTER TABLE Rental_car ADD INDEX FKRental_car964957 (user_id), ADD CONSTRAINT FKRental_car964957 FOREIGN KEY (user_id) REFERENCES user_profile (user_id);
ALTER TABLE ticket_bboking ADD INDEX FKticket_bbo375159 (user_id), ADD CONSTRAINT FKticket_bbo375159 FOREIGN KEY (user_id) REFERENCES user_profile (user_id);
ALTER TABLE Insurance ADD INDEX FKInsurance991042 (user_id), ADD CONSTRAINT FKInsurance991042 FOREIGN KEY (user_id) REFERENCES user_profile (user_id);
ALTER TABLE Guide ADD INDEX FKGuide120398 (user_id), ADD CONSTRAINT FKGuide120398 FOREIGN KEY (user_id) REFERENCES user_profile (user_id);
